import { qs, qsa } from "./dom.js";

// Mapa central de referências do DOM. Resolver tudo num único lugar evita
// `querySelector` espalhado pelas views e falha cedo se o HTML mudar.

/** @typedef {ReturnType<typeof bindRefs>} UIRefs */

/** @returns {Record<string, any>} */
export function bindRefs() {
  return {
    mainMenuButton: qs("#main-menu-button"),
    mainMenuPanel: qs("#main-menu-panel"),
    mainMenuCurrent: qs("#main-menu-current"),
    navButtons: qsa(".nav-button"),
    views: qsa(".view"),
    todayLabel: qs("#today-label"),
    todayMetrics: qs("#today-metrics"),
    undoDeleteButton: qs("#undo-delete-button"),
    routineFormPanel: qs("#routine-form-panel"),
    routineForm: qs("#routine-form"),
    routineFormTitle: qs("#routine-form-title"),
    routineFormModeLabel: qs("#routine-form-mode-label"),
    routineId: qs("#routine-id"),
    routineWeekday: qs("#routine-weekday"),
    routineStartTime: qs("#routine-start-time"),
    routineEndTime: qs("#routine-end-time"),
    routineSubject: qs("#routine-subject"),
    routineTeacher: qs("#routine-teacher"),
    routineRoom: qs("#routine-room"),
    routineRoomLegacyWarning: qs("#routine-room-legacy-warning"),
    routineStudentCount: qs("#routine-student-count"),
    routineDevices: qs("#routine-devices"),
    routineNewDevice: qs("#routine-new-device"),
    routineNotes: qs("#routine-notes"),
    routineFeedback: qs("#routine-form-feedback"),
    saveRoutineButton: qs("#save-routine-button span"),
    clearRoutineForm: qs("#clear-routine-form"),
    addDeviceToRoutine: qs("#add-device-to-routine"),
    todaySummary: qs("#today-summary"),
    todayRoutines: qs("#today-routines"),
    weekRoutines: qs("#week-routines"),
    routineFilter: qs("#routine-filter"),
    routineSort: qs("#routine-sort"),
    filterTimeStart: qs("#filter-time-start"),
    filterTimeEnd: qs("#filter-time-end"),
    filterTeacher: qs("#filter-teacher"),
    filterRoom: qs("#filter-room"),
    filterResultsCount: qs("#filter-results-count"),
    filterClearAll: qs("#filter-clear-all"),
    teachersDatalist: qs("#teachers-list"),
    subjectsDatalist: qs("#subjects-list"),
    teacherForm: qs("#teacher-form"),
    teacherId: qs("#teacher-id"),
    teacherName: qs("#teacher-name"),
    teacherFeedback: qs("#teacher-feedback"),
    teachersListPanel: qs("#teachers-list-panel"),
    roomForm: qs("#room-form"),
    roomId: qs("#room-id"),
    roomName: qs("#room-name"),
    roomStudentCount: qs("#room-student-count"),
    roomFeedback: qs("#room-feedback"),
    roomsListPanel: qs("#rooms-list-panel"),
    deviceForm: qs("#device-form"),
    deviceId: qs("#device-id"),
    deviceName: qs("#device-name"),
    deviceFeedback: qs("#device-feedback"),
    devicesListPanel: qs("#devices-list-panel"),
    settingsFeedback: qs("#settings-feedback"),
    exportDataButton: qs("#export-data-button"),
    importDataTrigger: qs("#import-data-trigger"),
    importDataFile: qs("#import-data-file"),
    resetDataButton: qs("#reset-data-button"),
    maintenanceResultsCount: qs("#maintenance-results-count"),
    maintenanceSummary: qs("#maintenance-summary"),
    maintenanceFilter: qs("#maintenance-filter"),
    maintenanceFilterClear: qs("#maintenance-filter-clear"),
    maintenanceFilterType: qs("#maintenance-filter-type"),
    maintenanceFilterStatus: qs("#maintenance-filter-status"),
    maintenanceFilterPriority: qs("#maintenance-filter-priority"),
    maintenanceNew: qs("#maintenance-new"),
    maintenanceBulk: qs("#maintenance-bulk"),
    maintenanceExportCsv: qs("#maintenance-export-csv"),
    maintenanceExportJson: qs("#maintenance-export-json"),
    maintenanceImportFile: qs("#maintenance-import-file"),
    maintenanceTableWrap: qs("#maintenance-table-wrap"),
    notificationBellButton: qs("#notification-bell-button"),
    notificationBellBadge: qs("#notification-bell-badge"),
    notificationsStatus: qs("#notifications-status"),
    notificationsSettings: qs("#notifications-settings"),
    notificationsUpcoming: qs("#notifications-upcoming"),
    notificationsRecent: qs("#notifications-recent"),
    notificationsCalendar: qs("#notifications-calendar"),
    notificationsTestSound: qs("#notifications-test-sound"),
    notificationsMarkAll: qs("#notifications-mark-all"),
    notificationPopupRoot: qs("#notification-popup-root"),
  };
}
